### ISSUE TITLE
Intent Redirection Vulnerability using otp_autofill [BUG] 

### ISSUE THREAD

**Issue by marcos930807** [surfstudio/SurfGear#110]
Hi Surf Team.

## Describe the bug
After use your plugin for opt detection. Google send me a mail with this warning.

Intent RedirectionYour app(s) are vulnerable to Intent Redirection.To address this issue, follow the steps in this Google Help Center article.
--

## Steps to Reproduce

Simple add opt_autofill plugin to any project upload a binary to play store and wait. Google will send you a mail about it.

## What is the expected behavior?

The Plugins work great, the problem is that google do not allow applications with this type of vulnerability. and must be fixed before June 14, 2021.

**Comment by artem-zaitsev** [comment]
Thank you for issue! We'll add this to our task list.

**Comment by artem-zaitsev** [comment]
@marcos930807 We update package fo fix vulnerability
