### ISSUE TITLE
methods for opening and closing the BottomSheet

### ISSUE THREAD

**Issue by praharshchargelab** [surfstudio/SurfGear#122]
## What is the new or updated feature that you are suggesting?
The ability to programmatically open, minimize and close the bottomsheet

## Why should this feature be included?
Pretty much all applications of a bottomsheet require us to have control over the size and the state of this widget. There are many cases in which the sheet should get dismissed or maximized programmatically, which cannot be done as of now (at least not that I know of).

Tried using scrollController.animate, but that scrolls the contents of the sheet, and not the sheet's size.

**Comment by artem-zaitsev** [comment]
Thanks for issue. We'll take a closer look at this shortly.

**Comment by MbIXjkee** [comment]
Thx for issue. This is a fundamental departure from the standard bottomsheet behavior. I can only assume that such cases should be critically examined for compliance with the user experience.
