### ISSUE TITLE
Для пакета MWWM сделать вызов метода onLoad() до super.initState()

### ISSUE THREAD

**Issue by AndX2** [surfstudio/SurfGear#132]
Для пакета MWWM сделать вызов метода onLoad() до super.initState(),  исключая вызов build() до завершения метода onLoad() при синхронном использовании.
Кейс использования: предположим, что в сервисе приложения уже есть необходимые данные для рендера виджета. Логичным будет в onLoad получить эти данные и предоставить для рендера UI. Но в текущем решении сначала вызовется build() без данных, а затем, сразу же, повторный build() но уже с данными. Это лишний ререндер + необходимость обработать на один фрейм emptyState.
![image](https://user-images.githubusercontent.com/9535163/114227566-d47f3400-997d-11eb-9779-c23ba2049886.png)

**Comment by MbIXjkee** [comment]
Билд вызывается с пустыми данными не от положения до или после initState, а от того каким образом построена работа EntityState-ов.
