### ISSUE TITLE
[BUG] [Relation] не вызывается EntityStreamBuilder.errorBuilder если до получения ошибки не было данных в EntityState

### ISSUE THREAD

**Issue by AndX2** [surfstudio/SurfGear#145]
Если при загрузке экрана сразу получить ошибку и положить ее в EntityStreamedState.error(error); то в билдере EntityStreamBuilder не вызовется метод .errorBuilder, поскольку в стриме отсутствуют данные (контент).
Проблема возникает из-за этого условия в пакете:
![image](https://user-images.githubusercontent.com/9535163/114987904-5ef3f600-9e9e-11eb-9b50-44295d0a2f54.png)
Временным решением может быть передача вместе с ошибкой дополнительного объекта данных стрима:
![image](https://user-images.githubusercontent.com/9535163/114988139-a7131880-9e9e-11eb-88c5-4f5b0eb97cc1.png)
но необходимость аллокации дополнительного объекта и невозможность использовать метод .error(error) - <ИМХО> баг, требующий исправления.

**Comment by IlyaMax** [comment]
По-моему это можно решить если добавить в EntityState геттер hasError. Если нет, то создам отдельную issue. Потому что каждый раз вызывать value?.hasError ?? false не очень удобно

**Comment by IlyaMax** [comment]
@AndX2 Я правильно понял?

**Comment by grafovdenis** [comment]
Fixed in [0.0.4-dev.3](https://github.com/surfstudio/SurfGear/commit/bc6d89103241ead376d86c62f23bc65e7c920a6d#diff-8a013da56a4d2aa9ed3972cda234e4f594f98cfe3f662a9ccb71d3fda6f95e4cR90).
