### ISSUE TITLE
Relation 3.0 backlog

### ISSUE THREAD

**Issue by IlyaMax** [surfstudio/SurfGear#217]
We can try to remove nullable from `StreamedStateBuilder` if we extend `StreamBuilderBase` with our own model which has not nullable data.

**Comment by artem-zaitsev** [comment]
It is interesting

**Comment by saturov** [comment]
Right now we have always nullable type for `StreamedStateBuilder` no matter if it's nullable or not inside the `StreamedState`. It's not rational I think. I prefer to control nullability of `StreamedStateBuilder`.

```dart 
final Widget Function(BuildContext, T?) builder;
```
