### ISSUE TITLE
Code error 

### ISSUE THREAD

**Issue by nikitadol** [surfstudio/SurfGear#23]
На хабре не дают написать, так напишу здесь

Вы немного ошиблись с удалением слушателей
В статье и в репозитории

https://github.com/surfstudio/SurfGear/blob/24593598b207190504b865a78a4cceb84164d9dd/packages/keyboard_listener/lib/src/keyboard_listener.dart#L104-L117

**Comment by pretorean** [comment]
В чем именно ошибка, поясните пожалуйста.

**Comment by nikitadol** [comment]
@pretorean 
Во всех трёх методах вы удаляете слушателей из `_changeListeners`, хотя нужно и из `_showListeners`, и из `_hideListeners `

**Comment by artem-zaitsev** [comment]
Ага, учтем!

**Comment by knightsforce** [comment]
Спасибо. Исправлю.
