### ISSUE TITLE
 [BUG] relation: 4.0.0-dev.1 не работает передача StreamedAction как функция обратного вызова

### ISSUE THREAD

**Issue by knightsforce** [surfstudio/SurfGear#246]
Приходится писать:
![image](https://user-images.githubusercontent.com/7579063/121806563-a275a100-cc50-11eb-9989-03b607f8a02e.png)

Иначе:
![image](https://user-images.githubusercontent.com/7579063/121806577-adc8cc80-cc50-11eb-9851-426140a99eeb.png)

И передавать null
![image](https://user-images.githubusercontent.com/7579063/121806583-bc16e880-cc50-11eb-8659-435bfc35b70d.png)

**Comment by IlyaMax** [comment]
@knightsforce Тебе нужно сделать onPressNext типа VoidAction. А в вмке bindVoid. Вроде можно закрывать
