### ISSUE TITLE
[BUG] bottom_sheet: LateError on first build with open keyboard

### ISSUE THREAD

**Issue by grafovdenis** [surfstudio/SurfGear#250]
Seems like [_controller](https://github.com/surfstudio/SurfGear/blob/main/packages/bottom_sheet/lib/src/flexible_bottom_sheet.dart#L280) has not been initialized since this line were executed [before _controller initialization](https://github.com/surfstudio/SurfGear/blob/main/packages/bottom_sheet/lib/src/flexible_bottom_sheet.dart#L168&L183).

**Comment by MbIXjkee** [comment]
Moved to package repo
