### ISSUE TITLE
Не работает пример mwwm

### ISSUE THREAD

**Issue by yourmaker0** [surfstudio/SurfGear#72]
После авторизации в гитхабе 404 ошибка и дальше ничего не происходит
![image](https://user-images.githubusercontent.com/40912672/105362097-a9116680-5c24-11eb-9806-909bfcf58f41.png)
Консоль `I/Timeline(16445): Timeline: Activity_launch_request time:490000328`
Flutter doctor 
```
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 1.22.4, on Microsoft Windows [Version 10.0.18363.1316], locale ru-KZ)

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
[!] Android Studio (version 4.1.0)
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
[√] Connected device (1 available)

! Doctor found issues in 1 category.
```

**Comment by pretorean** [comment]
в readme к этому примеру приведены указания о настройке github аккаунта и о заполнении констант your-client-id и your-client-secret.
Вы выполнили это указание перед запуском примера?

**Comment by yourmaker0** [comment]
Мое упущение
